// cfg for sql we are following:

//bnf form:

// <SQL> -> <STMT> |<STMT> <SQL>
// <STMT> -> <SELECT_STMT> | <INSERT_STMT> | <DELETE_STMT>

// <SELECT_STMT> -> SELECT <LIST> FROM <TABLE> <WHERE_OPT> <ORDER_BY_OPT> <GROUP_BY_OPT>;

// <LIST> -> * | <ATTR_LIST>

// <TABLE> -> IDENTIFIER

// <ATTR_LIST> -> IDENTIFIER| <ATTR_LIST>,IDENTIFIER



// <WHERE_OPT> -> WHERE <CONDITION> | ε

//<CONDITION> -> <CONDITION> OR <AND_CONDITION> | <AND_CONDITION>

// <AND_CONDITION> -> <AND_CONDITION> AND <NOT_CONDITION> | <NOT_CONDITION>

// <NOT_CONDITION> -> NOT <NOT_CONDITION> | (<CONDITION>) | IDENTIFIER <OP> <LITERAL>


// <OP> -> = | > | <
// <LITERAL> -> NUMBER | STRING

// <ORDER_BY_OPT> -> ORDER BY <LIST> | ε
// <GROUP_BY_OPT> -> GROUP BY <LIST> | ε

//<INSERT_STMT> -> INSERT INTO <TABLE> (LIST) VALUES (<VALUE_LIST>) ;

// <INSERT_STMT> -> INSERT INTO <TABLE> VALUES (<VALUE_LIST>) ;

// <VALUE_LIST> -> <LITERAL> | <VALUE_LIST>,<LITERAL>


// <DELETE_STMT> -> DELETE FROM <TABLE> WHERE IDENTIFIER <OP> <LITERAL>;



//LL(1) compatible:


//<SQL> -> <STMT> <SQL_TAIL>
//<SQL_TAIL> -> <STMT><SQL_TAIL> | ε

//<STMT> -> <SELECT_STMT> | <INSERT_STMT> | <DELETE_STMT>

//<SELECT_STMT> -> SELECT <LIST> FROM <TABLE> <WHERE_OPT> <ORDER_BY_OPT> <GROUP_BY_OPT>;

// <LIST> -> * | <ATTR_LIST>

// <TABLE> -> IDENTIFIER

// <ATTR_LIST> → IDENTIFIER <ATTR_LIST_TAIL>
// <ATTR_LIST_TAIL> → , IDENTIFIER <ATTR_LIST_TAIL> | ε

// <WHERE_OPT> -> WHERE <CONDITION> | ε

// <CONDITION> → <AND_CONDITION> <CONDITION_TAIL>
// <CONDITION_TAIL> → OR <AND_CONDITION> <CONDITION_TAIL> | ε

// <AND_CONDITION> → <NOT_CONDITION> <AND_CONDITION_TAIL>
// <AND_CONDITION_TAIL> → AND <NOT_CONDITION> <AND_CONDITION_TAIL> | ε

// <NOT_CONDITION> → NOT <NOT_CONDITION> | (<CONDITION>) | IDENTIFIER <OP> <LITERAL>

// <OP> → = | > | <

// <LITERAL> → NUMBER | STRING

// <ORDER_BY_OPT> → ORDER BY <LIST> | ε
// <GROUP_BY_OPT> → GROUP BY <LIST> | ε

//<INSERT_STMT> -> INSERT INTO <TABLE> <INSERT_TAIL>
//<INSERT_TAIL> -> (LIST) VALUES (<VALUE_LIST>) ; | VALUES (<VALUE_LIST>) ;

//<VALUE_LIST> → <LITERAL> <VALUE_LIST_TAIL>
//<VALUE_LIST_TAIL> → , <LITERAL> <VALUE_LIST_TAIL> | ε

//<DELETE_STMT> -> DELETE FROM <TABLE> WHERE IDENTIFIER <OP> <LITERAL>;
