// cfg for sql we are following:

//bnf form:

// <SQL> -> <STMT> |<STMT> <SQL>
// <STMT> -> <SELECT> | <INSERT> | <DELETE>

// <SELECT> -> SELECT <LIST> FROM <TABLE> <WHERE_OPT> <ORDER_BY_OPT> <GROUP_BY_OPT>;

// <LIST> -> * | <ATTR_LIST>

// <TABLE> -> IDENTIFIER

// <ATTR_LIST> -> IDENTIFIER| <ATTR_LIST>,IDENTIFIER



// <WHERE_OPT> -> WHERE <CONDITION> | ε

//<CONDITION> -> <CONDITION> OR <AND_CONDITION> | <AND_CONDITION>

// <AND_CONDITION> -> <AND_CONDITION> AND <NOT_CONDITION> | <NOT_CONDITION>

// <NOT_CONDITION> -> NOT <NOT_CONDITION> | (<CONDITION>) | IDENTIFIER <OP> <LITERAL>


// <OP> -> = | > | <
// <LITERAL> -> NUMBER | STRING

// <ORDER_BY_OPT> -> ORDER BY <LIST> | ε
// <GROUP_BY_OPT> -> GROUP BY <LIST> | ε

//<INSERT> -> INSERT INTO <TABLE> (LIST) VALUES (<VALUE_LIST>) ;

// <INSERT> -> INSERT INTO <TABLE> VALUES (<VALUE_LIST>) ;

// <VALUE_LIST> -> <LITERAL> | <VALUE_LIST>,<LITERAL>

// <DELETE> -> DELETE FROM <TABLE> <WHERE IDENTIFIER <OP> <LITERAL>;

// <DELETE> -> DELETE FROM <TABLE> <WHERE> <CONDITION>;

